### ISSUE TITLE
using this with two id fields is throwing errors

### ISSUE THREAD

**Issue by ponypaw** [ramiel/mongoose-sequence#104]
I've been trying to make this work with two schemas in my app and I cant seem to figure it out.  I found a reference to someone else with an issue here and used their solution as a guide but its not working. I have 2 schemas set up, "userSchema" and "petSchema". Below each schema I have:

userSchema.plugin(AutoIncrement, {id: 'counters',inc_field: 'user', disable_hooks: true});

and 

 petSchema.plugin(AutoIncrement, {id: 'petCounters', inc_field: 'pets'});

as a part of them both, the schemas have:

id: {
    type: Number,
    primaryKey: true
  },

and at the end, 

_id: false

But when I try to use the schemas, I get this error:

(node:5168) UnhandledPromiseRejectionWarning: MongooseError: document must have an _id before saving
    at Timeout._onTimeout (C:\Users\ponyp\Desktop\MiwV2\node_modules\mongoose\lib\model.js:268:18)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:5168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Can you please help me figure out what's going wrong? I am still a beginner and I'm having a hard time figuring out what's up. I gather it's not giving the newly made pet an ID number but I can't tell why.

**Comment by ramiel** [comment]
Can you send the schemas (relevant part) and the plugin instantiation? Can you please try to better format the code (use  backtick \` or the button `< >`).    
Can you try to assign two different ids to the autoIncrement? Something like this

```js
userSchema.plugin(AutoIncrement, {id: 'user_id_counter', inc_field: 'id' });
petSchema.plugin(AutoIncrement, {id: 'pet_id_counter', inc_field: 'id' });
```

**Comment by ramiel** [comment]
Also, is `primaryKey: true` part of mongoose :thinking: ? I think it's not, you have to define an index on the `id` field if you want to simulate the effect of a primary key.
