### ISSUE TITLE
TypeError: doc.set is not a function

### ISSUE THREAD

**Issue by 7ameed** [ramiel/mongoose-sequence#94]
each time i try to save a new document i get the following error
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: doc.set is not a function
    at sequence._setNextCounter (/media/hameed/27B51D3A60C5B106/yaqeen-backend/node_modules/mongoose-sequence/lib/sequence.js:238:17)
    at /media/hameed/27B51D3A60C5B106/yaqeen-backend/node_modules/async/dist/async.js:4617:26
    at _counterModel.findOneAndUpdate (/media/hameed/27B51D3A60C5B106/yaqeen-backend/node_modules/mongoose-sequence/lib/sequence.js:340:18)
    at /media/hameed/27B51D3A60C5B106/yaqeen-backend/node_modules/mongoose/lib/model.js:4842:16
    at /media/hameed/27B51D3A60C5B106/yaqeen-backend/node_modules/mongoose/lib/model.js:4842:16
    at /media/hameed/27B51D3A60C5B106/yaqeen-backend/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
    at /media/hameed/27B51D3A60C5B106/yaqeen-backend/node_modules/mongoose/lib/model.js:4865:21
    at _hooks.execPost (/media/hameed/27B51D3A60C5B106/yaqeen-backend/node_modules/mongoose/lib/query.js:4419:11)
    at /media/hameed/27B51D3A60C5B106/yaqeen-backend/node_modules/kareem/index.js:135:16
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at /media/hameed/27B51D3A60C5B106/yaqeen-backend/node_modules/mongoose/lib/model.js:4844:13
    at /media/hameed/27B51D3A60C5B106/yaqeen-backend/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
    [... lines matching original stack trace ...]
    at process._tickCallback **(internal/process/next_tick.js:61:11)
```
mongo model
```
var mongoose = require('mongoose-fill')
const AutoIncrement = require('mongoose-sequence')(mongoose);
const constants = require('../config/constants');

const batchSchema = new mongoose.Schema({
    _id: Number,
    set: {
        type: mongoose.Schema.Types.Number,
        ref: 'ShareSet',
        required: true
    },
    suggestions: {
        type: [mongoose.Schema.Types.ObjectId],
        ref: 'Suggestion',
        required: true
    },
    category: {
        type: mongoose.Schema.Types.Number,
        ref: 'Category',
        required: true
    },
    batchClass: {
        type: String,
        default: constants.BATCH_TYPES.VERIFY,
        required: true
    },
    keywords: {
        type: String,
        default: ''
    },
    createdAt: {
        type: Date,
        default: Date.now,
        required: true
    },
    updatedAt: {
        type: Date,
        default: Date.now,
        required: true
    }
}, {
    _id: false,
    toJSON: { virtuals: true },
    toObject: { virtuals: true }
});

batchSchema.plugin(AutoIncrement, { id: 'batchCounter' })


batchSchema.pre('update', function (next) {
    this.update({}, { $set: { updatedAt: new Date() } })
    next()
})

batchSchema.pre('findOneAndUpdate', function (next) {
    this.update({}, { $set: { updatedAt: new Date() } })
    next()
})

const Batch = mongoose.model('Batch', batchSchema);

module.exports = Batch
```

**Comment by ramiel** [comment]
Solved?

**Comment by 7ameed** [comment]
it was a mistake in my code
